name: Deploy to Deta

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init Deta CL
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
          echo "$HOME/.detaspace/bin" >> $GITHUB_PATH
          echo "SPACE_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}" >> $GITHUB_ENV
      - name: Push and Release
        run: |
          space link --id "${{ secrets.DETA_PROJECT_ID }}"
          space push
          space release --listed --confirm 
