name: Push to Space
on: [push, workflow_dispatch]

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: retry action
        id: retry
        uses: Wandalen/wretry.action@v1.3.0
        with: 
          attempt_limit : 100
          action: lizheming/deta-action@master
          with: |
            access_token: ${{ secrets.ACCESS_TOKEN }}
            id: ${{ secrets.PROJECT_ID }}
            listed: false
