name: Push to Space
on: push

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.my-action.outputs.outputs }}
    steps:
      - name: retry action
        uses: Wandalen/wretry.action@v1.3.0
        with: 
          attempt_limit : 100
          action: neobrains/space-deployment-github-action@v0.5
          with: |
            access_token: ${{ secrets.ACCESS_TOKEN }}
            project_id: ${{ secrets.PROJECT_ID }}
            space_push: true
            list_on_discovery: false
  output:
    runs-on: ubuntu-latest
    needs: push-to-space
    steps:
      - env:
          OUTPUT1: ${{ fromJSON( needs.job1.outputs.out ) }}
        run: echo "$OUTPUT1"
        
            
