name: Push to Space
on: [push, workflow_dispatch]

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: retry action
        id: retry
        uses: Wandalen/wretry.action@v1.3.0
        with: 
          attempt_limit : 100
          action: neobrains/space-deployment-github-action@v0.5
          with: |
            access_token: ${{ secrets.ACCESS_TOKEN }}
            project_id: ${{ secrets.PROJECT_ID }}
            space_push: true
            list_on_discovery: false
